FROM php:8.2-apache

RUN apt-get update && \
    apt-get install -y \
        # Install required packages
        curl \
        unzip && \
    # Clean up apt cache
    rm -rf /var/lib/apt/lists/* && \
    # Install PHP extensions
    docker-php-ext-install pdo pdo_mysql && \
    # Install and enable Apache modules
    a2enmod rewrite && \
    echo "ServerSignature Off\nServerTokens Prod" > /etc/apache2/conf-available/security.conf && \
    a2enconf security && \
    sed -i 's/Options Indexes FollowSymLinks/Options FollowSymLinks/' /etc/apache2/apache2.conf && \
    # Configure Apache
    echo "upload_max_filesize=300M" > /usr/local/etc/php/conf.d/uploads.ini && \
    echo "post_max_size=300M" >> /usr/local/etc/php/conf.d/uploads.ini && \
    echo "memory_limit=512M" >> /usr/local/etc/php/conf.d/uploads.ini && \
    echo "max_execution_time=300" >> /usr/local/etc/php/conf.d/uploads.ini && \
    echo "expose_php = Off" > /usr/local/etc/php/conf.d/custom.ini && \
    echo "display_startup_errors = Off" >> /usr/local/etc/php/conf.d/custom.ini && \
    echo "disable_functions = phpinfo, system, exec, shell_exec, passthru" >> /usr/local/etc/php/conf.d/security.ini

WORKDIR /var/www/html

EXPOSE 80

RUN chown -R www-data:www-data /var/www/html